GET http://localhost:3000/api/ok

###
GET http://localhost:3000/api/users
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJraW55dWEiLCJyb2xlIjoiYWRtaW4iLCJleHAiOjE3MTgyMjgyMTJ9.TGq8URrLuD3TQlmciepjjMY1M3HivJ_cesQg85fTfwU

###
POST http://localhost:3000/api/users
Content-Type: application/json

{
    "id":1,
    "contact_phone":"+25434",
    "contact_email":"<EMAIL>",
    "contact_name":"<NAME>"
}
###
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
    "userId":1,
    "username":"kinyua",
    "password":"pass",
    "role":"admin"
    
}

###
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
    "username":"kinyua",
    "password":"pass"
}
###
GET http://localhost:3000/api/users
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJtb3NlcyIsInJvbGUiOiJ1c2VyIiwiZXhwIjoxNzE4MjA0MDc4fQ.PJ3hQ2afQCHAtlzSvnu_PlcL3TBRZZvjXruEkRyJGaU
###
GET http://localhost:3000/api/state

Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJraW55dWEiLCJyb2xlIjoiYWRtaW4iLCJleHAiOjE3MTgyNjAwMjl9.LxIpl0eSzWl3m8hzzM3N3LcItUzVtSCC_d1XP6Z0-G4