
GET http://localhost:3000/api/orders
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJraW55dWEiLCJyb2xlIjoiYWRtaW4iLCJleHAiOjE3MTg2MDkwNDR9.EawLKzzzuNoi909C03N4_IRO84N4rF8Eswa-XmNTj1E
###

GET http://localhost:3000/api/users/1
###

PUT http://localhost:3000/api/users/1
Content-Type: application/json
  {
    "id": 4,
    "name": "moses",
    "contact_phone": "+25407999",
    "email": "@gmail",
    "email_verified": true,
    "confirmation_code": "34",
    "password": "845",
    "created_at": "2001-03-03T00:00:00.000Z",
    "updated_at": "2007-03-02T00:00:00.000Z",
    "address": "4553",
    "comment": "good",
    "driver": "alekii",
    "orders": "beef",
    "restaurant_owner": "kadesh"
  }

###
POST http://localhost:3000/api/city
Content-Type: application/json
{
     "id": 5,
    "name": "moses",
    "contact_phone": "+25407999",
    "email": "@gmail",
    "email_verified": true,
    "confirmation_code": "34",
    "password": "845",
    "created_at": "2001-03-03T00:00:00.000Z",
    "updated_at": "2007-03-02T00:00:00.000Z",
    "address": "4553",
    "comment": "good",
    "driver": "alekii",
    "orders": "beef",
    "restaurant_owner": "kadesh"  
    
}
  






























###
GET http://localhost:3000/api/users
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJraW55dWEiLCJyb2xlIjoiYWRtaW4iLCJleHAiOjE3MTgyMjgyMTJ9.TGq8URrLuD3TQlmciepjjMY1M3HivJ_cesQg85fTfwU

###
POST http://localhost:3000/api/users
Content-Type: application/json

{
    "id":1,
    
}
###
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
    "userId":1,
    "username":"kinyua",
    "password":"pass",
    "role":"admin"
    
}

###
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
    "username":"kinyua",
    "password":"pass"
}
###
GET http://localhost:3000/api/users
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJraW55dWEiLCJyb2xlIjoiYWRtaW4iLCJleHAiOjE3MTgyOTYzODF9.Ves_G6tX4E759x_07R9XenPB9sDtV9-eEGKyNBFSpjk
###
GET http://localhost:3000/api/state

Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJraW55dWEiLCJyb2xlIjoiYWRtaW4iLCJleHAiOjE3MTgzODAyMjF9.MiWjwwqcoirMtd3wLa0xFrD2lj_aCU8fO2Ep8st8YXQ